# Python for Data Science — Fundamentals

**Data Science Journey 2026 — @datasciencehorizon**

A complete, hands-on reference notebook covering Python fundamentals through NumPy and Pandas — the foundation everything later in this series builds on.

## Table of Contents

1. [Introduction](#1.-Introduction)
2. [Python Data Types](#2.-Python-Data-Types)
3. [Type Conversion](#3.-Type-Conversion)
4. [Python Operators](#4.-Python-Operators)
5. [Python Data Structures](#5.-Python-Data-Structures)
6. [Functions and Loops](#6.-Functions-and-Loops)
7. [NumPy Basics](#7.-NumPy-Basics)
8. [NumPy Operations](#8.-NumPy-Operations)
9. [Pandas Series](#9.-Pandas-Series)
10. [Pandas DataFrame](#10.-Pandas-DataFrame)
11. [Data Selection & Filtering](#11.-Data-Selection-&-Filtering)
12. [Handling Missing Values](#12.-Handling-Missing-Values)
13. [GroupBy](#13.-GroupBy)
14. [Practical Exercises](#14.-Practical-Exercises)
15. [Mini Project](#15.-Mini-Project)


## 1. Introduction

Python is the most widely used language in data science — readable syntax, a massive ecosystem of libraries, and the same language for data cleaning, analysis, machine learning, and deployment.

This notebook builds up from plain Python (data types, operators, data structures, functions, loops) to the two libraries you'll use in almost every project: **NumPy** (fast numerical arrays) and **Pandas** (tabular data). Each section is short, runnable, and builds on the one before it — by the end, you'll do a small end-to-end mini project using everything covered.

## 2. Python Data Types

Every value in Python has a type. The core built-in types you'll use constantly: `int`, `float`, `str`, `bool`, and `None`.

In [1]:
age = 28                 # int
price = 499.99            # float
name = "Nidhi"             # str
is_subscribed = True       # bool
missing_value = None       # NoneType

for value in [age, price, name, is_subscribed, missing_value]:
    print(f"{value!r:>10}  ->  {type(value).__name__}")

        28  ->  int
    499.99  ->  float
   'Nidhi'  ->  str
      True  ->  bool
      None  ->  NoneType


In [2]:
# Strings support rich built-in behaviour
channel = "Data Science Horizon"
print(channel.upper())
print(channel.lower())
print(channel.split())
print(len(channel))
print(channel.replace("Horizon", "Journey"))

DATA SCIENCE HORIZON
data science horizon
['Data', 'Science', 'Horizon']
20
Data Science Journey


## 3. Type Conversion

Python converts types **implicitly** in some cases (e.g. `int + float`), but most of the time you'll convert **explicitly** using `int()`, `float()`, `str()`, and `bool()`.

In [3]:
# Implicit conversion
result = 5 + 2.5   # int + float -> float automatically
print(result, type(result).__name__)

# Explicit conversion
score_text = "87"
score_num = int(score_text)        # str -> int
print(score_num + 3)

price_str = str(499.99)            # float -> str
print("Price: " + price_str)

print(float("3.14"))               # str -> float
print(bool(0), bool(1), bool(""), bool("hi"))   # truthiness rules

7.5 float
90
Price: 499.99
3.14
False True False True


In [4]:
# A common gotcha: this raises an error, shown here safely with try/except
try:
    int("87.5")   # int() can't parse a decimal string directly
except ValueError as e:
    print("ValueError caught:", e)

print(int(float("87.5")))   # the fix: go through float() first

ValueError caught: invalid literal for int() with base 10: '87.5'
87


## 4. Python Operators

Arithmetic, comparison, logical, and membership operators — the building blocks of every condition and calculation you'll write.

In [5]:
a, b = 17, 5

print("Arithmetic:")
print(a + b, a - b, a * b, a / b, a // b, a % b, a ** 2)

print("\nComparison:")
print(a > b, a == b, a != b, a <= b)

print("\nLogical:")
print(True and False, True or False, not True)

print("\nMembership:")
fruits = ["apple", "banana", "mango"]
print("banana" in fruits, "grape" not in fruits)

Arithmetic:
22 12 85 3.4 3 2 289

Comparison:
True False True False

Logical:
False True False

Membership:
True True


## 5. Python Data Structures

Four core containers: **list** (ordered, mutable), **tuple** (ordered, immutable), **dict** (key-value pairs), and **set** (unique, unordered).

In [6]:
# List -- ordered, mutable
scores = [85, 92, 78, 92, 60]
scores.append(100)
scores[0] = 90
print("List:", scores, "| sorted:", sorted(scores))

# Tuple -- ordered, immutable
point = (10, 20)
print("Tuple:", point, "| x =", point[0])

# Dict -- key-value pairs
student = {"name": "Aarav", "age": 21, "grade": "A"}
student["city"] = "Delhi"
print("Dict:", student, "| keys:", list(student.keys()))

# Set -- unique values only
unique_scores = set(scores)
print("Set:", unique_scores)

List: [90, 92, 78, 92, 60, 100] | sorted: [60, 78, 90, 92, 92, 100]
Tuple: (10, 20) | x = 10
Dict: {'name': 'Aarav', 'age': 21, 'grade': 'A', 'city': 'Delhi'} | keys: ['name', 'age', 'grade', 'city']
Set: {100, 78, 60, 90, 92}


In [7]:
# Slicing works on lists, tuples, and strings the same way
letters = ["a", "b", "c", "d", "e", "f"]
print(letters[1:4])     # index 1 up to (not including) 4
print(letters[:3])      # first 3
print(letters[-2:])     # last 2
print(letters[::2])     # every 2nd element

['b', 'c', 'd']
['a', 'b', 'c']
['e', 'f']
['a', 'c', 'e']


## 6. Functions and Loops

Functions package reusable logic. Loops (`for`, `while`) repeat it. List comprehensions do both compactly.

In [8]:
def celsius_to_fahrenheit(temp_c, round_to=1):
    """Convert Celsius to Fahrenheit, rounded to `round_to` decimal places."""
    return round(temp_c * 9 / 5 + 32, round_to)

print(celsius_to_fahrenheit(0))
print(celsius_to_fahrenheit(100))
print(celsius_to_fahrenheit(37, round_to=2))

32.0
212.0
98.6


In [9]:
# for loop
for temp in [0, 20, 37, 100]:
    print(f"{temp}C -> {celsius_to_fahrenheit(temp)}F")

# while loop
countdown = 3
while countdown > 0:
    print("Countdown:", countdown)
    countdown -= 1
print("Liftoff!")

0C -> 32.0F
20C -> 68.0F
37C -> 98.6F
100C -> 212.0F
Countdown: 3
Countdown: 2
Countdown: 1
Liftoff!


In [10]:
# List comprehension -- the compact, Pythonic way to build a list from a loop
squares = [n ** 2 for n in range(1, 8)]
print(squares)

evens_only = [n for n in range(20) if n % 2 == 0]
print(evens_only)

# lambda -- a small anonymous function, often used with sorting or map/filter
pairs = [("b", 2), ("a", 3), ("c", 1)]
print(sorted(pairs, key=lambda p: p[1]))

[1, 4, 9, 16, 25, 36, 49]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[('c', 1), ('b', 2), ('a', 3)]


## 7. NumPy Basics

NumPy's core object is the **array** — like a Python list, but fixed-type and dramatically faster for numerical work, because operations run in optimized C code instead of a Python loop.

In [11]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a, type(a), a.dtype, a.shape)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print("shape:", matrix.shape, "| ndim:", matrix.ndim, "| size:", matrix.size)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
[[1 2 3]
 [4 5 6]]
shape: (2, 3) | ndim: 2 | size: 6


In [12]:
# Common array creation shortcuts
print(np.zeros((2, 3)))
print(np.ones(4))
print(np.arange(0, 10, 2))          # start, stop, step
print(np.linspace(0, 1, 5))         # 5 evenly spaced points between 0 and 1
print(np.random.seed(42) or np.random.rand(3))   # 3 random numbers in [0,1)

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[0.37454012 0.95071431 0.73199394]


## 8. NumPy Operations

The real power of NumPy: **vectorized** operations (no explicit loop needed) and **broadcasting** (operations between arrays of different, compatible shapes).

In [13]:
arr = np.array([10, 20, 30, 40, 50])

print(arr + 5)          # vectorized addition -- applies to every element
print(arr * 2)
print(arr[arr > 25])    # boolean indexing -- keep only elements matching a condition

print("sum:", arr.sum(), "| mean:", arr.mean(), "| std:", round(arr.std(), 2), "| max:", arr.max())

[15 25 35 45 55]
[ 20  40  60  80 100]
[30 40 50]
sum: 150 | mean: 30.0 | std: 14.14 | max: 50


In [14]:
# Broadcasting: a smaller array "stretches" to match a bigger one's shape
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_add = np.array([10, 20, 30])

print(matrix + row_add)     # row_add is applied to every row
print(matrix.reshape(9, 1)[:4])   # reshape into a different compatible shape
print(matrix.T)             # transpose

[[11 22 33]
 [14 25 36]
 [17 28 39]]
[[1]
 [2]
 [3]
 [4]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## 9. Pandas Series

A **Series** is a single labelled column of data — think of it as a NumPy array with an index attached.

In [15]:
import pandas as pd

prices = pd.Series([499, 699, 999, 1299], index=["Basic", "Standard", "Pro", "Enterprise"])
print(prices)
print("\nAccess by label:", prices["Pro"])
print("Access by position:", prices.iloc[0])
print("\nMean price:", prices.mean())
print("Prices above 700:\n", prices[prices > 700])

Basic          499
Standard       699
Pro            999
Enterprise    1299
dtype: int64

Access by label: 999
Access by position: 499

Mean price: 874.0
Prices above 700:
 Pro            999
Enterprise    1299
dtype: int64


## 10. Pandas DataFrame

A **DataFrame** is a full table — multiple named columns, each a Series, all sharing the same index. This is the workhorse structure for almost all tabular data science.

We'll build one small synthetic dataset here and reuse it for the rest of this notebook.

In [16]:
data = {
    "product": ["Widget A", "Widget B", "Widget C", "Widget D", "Widget E", "Widget F"],
    "category": ["Tools", "Tools", "Electronics", "Electronics", "Home", "Home"],
    "price": [19.99, 24.99, 199.0, 149.5, 39.99, None],
    "units_sold": [120, 85, 40, 55, None, 30],
    "rating": [4.5, 4.2, 4.8, 3.9, 4.1, 4.6],
}

df = pd.DataFrame(data)
df

,product,category,price,units_sold,rating
0,Widget A,Tools,19.99,120.0,4.5
1,Widget B,Tools,24.99,85.0,4.2
2,Widget C,Electronics,199.00,40.0,4.8
3,Widget D,Electronics,149.50,55.0,3.9
4,Widget E,Home,39.99,NaN,4.1
5,Widget F,Home,NaN,30.0,4.6


In [17]:
print("Shape:", df.shape)
print("\nColumns:", list(df.columns))
print("\nDtypes:\n", df.dtypes)
df.head(3)

Shape: (6, 5)

Columns: ['product', 'category', 'price', 'units_sold', 'rating']

Dtypes:
 product        object
category       object
price         float64
units_sold    float64
rating        float64
dtype: object


,product,category,price,units_sold,rating
0,Widget A,Tools,19.99,120.0,4.5
1,Widget B,Tools,24.99,85.0,4.2
2,Widget C,Electronics,199.00,40.0,4.8


In [18]:
df.describe()   # quick summary statistics for all numeric columns

,price,units_sold,rating
count,5.000000,5.000000,6.000000
mean,86.694000,66.000000,4.350000
std,82.151236,36.640142,0.339116
min,19.990000,30.000000,3.900000
25%,24.990000,40.000000,4.125000
50%,39.990000,55.000000,4.350000
75%,149.500000,85.000000,4.575000
max,199.000000,120.000000,4.800000


## 11. Data Selection & Filtering

`loc` selects by label, `iloc` selects by position, and boolean masks filter rows by condition — the three tools you'll use in almost every pandas script.

In [19]:
print(df["product"])                 # single column -> Series
print(type(df[["product", "price"]])) # multiple columns -> DataFrame
df[["product", "price"]]

0    Widget A
1    Widget B
2    Widget C
3    Widget D
4    Widget E
5    Widget F
Name: product, dtype: object
<class 'pandas.core.frame.DataFrame'>


,product,price
0,Widget A,19.99
1,Widget B,24.99
2,Widget C,199.00
3,Widget D,149.50
4,Widget E,39.99
5,Widget F,NaN


In [20]:
print(df.loc[0])          # row by label (here, label == position since default index)
print(df.iloc[0:3])       # rows by position, slice
df.loc[df["category"] == "Electronics"]   # boolean filtering

product       Widget A
category         Tools
price            19.99
units_sold       120.0
rating             4.5
Name: 0, dtype: object
    product     category   price  units_sold  rating
0  Widget A        Tools   19.99       120.0     4.5
1  Widget B        Tools   24.99        85.0     4.2
2  Widget C  Electronics  199.00        40.0     4.8


,product,category,price,units_sold,rating
2,Widget C,Electronics,199.0,40.0,4.8
3,Widget D,Electronics,149.5,55.0,3.9


In [21]:
# Combine conditions with & (and) / | (or) -- each condition needs parentheses
df[(df["category"] == "Tools") & (df["rating"] > 4.3)]

,product,category,price,units_sold,rating
0,Widget A,Tools,19.99,120.0,4.5


## 12. Handling Missing Values

Real data is messy. `isna()` finds missing values, `dropna()` removes them, and `fillna()` replaces them — the choice between dropping and filling depends on how much data you can afford to lose.

In [22]:
print(df.isna().sum())        # count missing values per column
df[df.isna().any(axis=1)]     # show only rows with at least one missing value

product       0
category      0
price         1
units_sold    1
rating        0
dtype: int64


,product,category,price,units_sold,rating
4,Widget E,Home,39.99,NaN,4.1
5,Widget F,Home,NaN,30.0,4.6


In [23]:
df_dropped = df.dropna()
print("Rows after dropna():", len(df_dropped), "of", len(df))

df_filled = df.copy()
df_filled["price"] = df_filled["price"].fillna(df_filled["price"].mean())
df_filled["units_sold"] = df_filled["units_sold"].fillna(0)
df_filled

Rows after dropna(): 4 of 6


,product,category,price,units_sold,rating
0,Widget A,Tools,19.990,120.0,4.5
1,Widget B,Tools,24.990,85.0,4.2
2,Widget C,Electronics,199.000,40.0,4.8
3,Widget D,Electronics,149.500,55.0,3.9
4,Widget E,Home,39.990,0.0,4.1
5,Widget F,Home,86.694,30.0,4.6


## 13. GroupBy

`groupby` splits a DataFrame into groups by a column's values, applies a calculation to each group, then combines the results — the classic "split-apply-combine" pattern.

In [24]:
df_filled.groupby("category")["price"].mean()

category
Electronics    174.250
Home            63.342
Tools           22.490
Name: price, dtype: float64

In [25]:
df_filled.groupby("category").agg(
    avg_price=("price", "mean"),
    total_units=("units_sold", "sum"),
    avg_rating=("rating", "mean"),
).round(2)

,avg_price,total_units,avg_rating
category,,,
Electronics,174.25,95.0,4.35
Home,63.34,30.0,4.35
Tools,22.49,205.0,4.35


## 14. Practical Exercises

A few short exercises, each with a worked solution, to lock in what we've covered.

**Exercise 1 — FizzBuzz:** print numbers 1-20, but print "Fizz" for multiples of 3, "Buzz" for multiples of 5, and "FizzBuzz" for multiples of both.

In [26]:
for n in range(1, 21):
    if n % 15 == 0:
        print("FizzBuzz")
    elif n % 3 == 0:
        print("Fizz")
    elif n % 5 == 0:
        print("Buzz")
    else:
        print(n)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz


**Exercise 2 — List comprehension:** given a list of words, return only those longer than 4 characters, in uppercase.

In [27]:
words = ["data", "science", "AI", "python", "ml", "notebook"]
result = [w.upper() for w in words if len(w) > 4]
print(result)

['SCIENCE', 'PYTHON', 'NOTEBOOK']


**Exercise 3 — DataFrame filtering:** from `df_filled`, find the single best-rated product priced under 100.

In [28]:
affordable = df_filled[df_filled["price"] < 100]
best_affordable = affordable.sort_values("rating", ascending=False).iloc[0]
print(best_affordable[["product", "price", "rating"]])

product    Widget F
price        86.694
rating          4.6
Name: 5, dtype: object


## 15. Mini Project — Sales Report Generator

Put it all together: load a slightly bigger synthetic sales dataset, clean it, and produce a short summary report using everything from this notebook.

In [29]:
import numpy as np
import pandas as pd

np.random.seed(1)
n = 24
sales = pd.DataFrame({
    "month": pd.date_range("2025-01-01", periods=n, freq="MS"),
    "region": np.random.choice(["North", "South", "East", "West"], size=n),
    "revenue": np.round(np.random.normal(50000, 12000, size=n), 2),
    "units": np.random.randint(100, 500, size=n),
})
# Introduce a few realistic missing values
sales.loc[[3, 10, 17], "revenue"] = np.nan
sales.head()

,month,region,revenue,units
0,2025-01-01,South,53828.47,413
1,2025-02-01,West,47007.56,183
2,2025-03-01,North,67545.30,266
3,2025-04-01,North,NaN,236
4,2025-05-01,West,46130.99,388


In [30]:
# Step 1: clean -- fill missing revenue with that region's average revenue
sales["revenue"] = sales.groupby("region")["revenue"].transform(lambda s: s.fillna(s.mean()))
print("Missing values remaining:", sales["revenue"].isna().sum())

Missing values remaining: 0


In [31]:
# Step 2: derive a new column -- revenue per unit
sales["revenue_per_unit"] = (sales["revenue"] / sales["units"]).round(2)
sales.head()

,month,region,revenue,units,revenue_per_unit
0,2025-01-01,South,53828.470,413,130.34
1,2025-02-01,West,47007.560,183,256.87
2,2025-03-01,North,67545.300,266,253.93
3,2025-04-01,North,47307.205,236,200.45
4,2025-05-01,West,46130.990,388,118.89


In [32]:
# Step 3: summarise by region -- the report
report = sales.groupby("region").agg(
    total_revenue=("revenue", "sum"),
    avg_revenue_per_month=("revenue", "mean"),
    total_units=("units", "sum"),
    avg_revenue_per_unit=("revenue_per_unit", "mean"),
).round(2).sort_values("total_revenue", ascending=False)

report

,total_revenue,avg_revenue_per_month,total_units,avg_revenue_per_unit
region,,,,
North,378457.64,47307.20,2825,149.58
South,361897.97,51699.71,2339,159.69
West,268411.32,53682.26,1463,210.25
East,197821.00,49455.25,1427,144.96


In [33]:
top_region = report.index[0]
print(f"Top-performing region: {top_region}")
print(f"Total revenue across all regions: {sales['revenue'].sum():,.2f}")
print(f"Overall average revenue per unit: {sales['revenue_per_unit'].mean():.2f}")

Top-performing region: North
Total revenue across all regions: 1,206,587.93
Overall average revenue per unit: 164.40


### Summary

In this notebook we covered every core Python building block a data scientist needs day to day — data types, conversion, operators, data structures, functions, and loops — then moved into **NumPy** for fast numerical arrays and **Pandas** for tabular data: building DataFrames, selecting and filtering, handling missing values, and grouping. The mini project tied it all together into a small, realistic reporting workflow.

This is exactly the foundation the rest of the *Data Science Journey 2026* series builds on — from here, Step 5 puts these same Pandas and NumPy skills to work on real exploratory data analysis.

---
More at [datasciencehorizon.com](https://datasciencehorizon.com) · Follow **@datasciencehorizon**
